CC=gcc
CFLAGS=-g -Wall -O0
SRC=catc.c
EXE=Catc

all: q

catc:
	$(CC) $(CFLAGS) catc.c -o Catc

termsend:
	$(CC) $(CFLAGS) termsend.c -o Termsend

two_or_one:
	$(CC) $(CFLAGS) two_or_one.c -o TwoOrOne

q:
	$(CC) $(CFLAGS) q1.c -o q1
